language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python ./USC/ParaCELLsys/plotParallelData_pos_newFormat.py

notifications:
  slack: sciinstitute:pBg7vSh32XVc9V94MPkQSeGk
